language: python
script: python manage.py
language:
  - python
before-install:
  - pip install -r requirements.txt
<<<<<<< HEAD
  - pip install black
  - pip install coveralls
script:
  - flake8 --max-line-length=100
  - black --check .
  - coverage run --source=home manage.py test home
after_success:
  - coveralls
=======
  - pip install flake8
  - pip install black
  - pip install coveralls
script:
  - black --check
  - flake8 --max-line-length=100
  - coverage run --source=home manage.py test home
after_success:
  - coveralls
>>>>>>> 9b370647b35c7b788f28c93babfbca47249eb874
