language: python
python:
  - "3.8"      # current default Python on Travis CI
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install --user -r requirements.txt --use-feature=2020-resolver
